# Generated by Django 2.2.19 on 2021-04-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='voice',
            field=models.IntegerField(default=0),
        ),
    ]
